### PR TITLE
ENH: Files add accepts unused filename filter

### PR DESCRIPTION
**Pull request by heaven00**
#49

### CODE REVIEW

**Comment by heaven00** [comment]
@whereswaldon I am not sure about the regex `.*` as default, it can be changed to `[a-zA-Z-0-9.-_]` that also works

```
>>> import re
>>> re.match('[a-zA-Z-0-9.-]*', 'ipfs.py')
<_sre.SRE_Match object; span=(0, 7), match='ipfs.py'>
>>> re.match('[a-zA-Z-0-9.-]*', 'go-ipfs.py')
<_sre.SRE_Match object; span=(0, 10), match='go-ipfs.py'>
>>> re.match('[a-zA-Z-0-9.-_]*', 'go-ipfs.py')
<_sre.SRE_Match object; span=(0, 10), match='go-ipfs.py'>
>>> re.match('[a-zA-Z-0-9.-_]*', 'go_ipfs.py')
<_sre.SRE_Match object; span=(0, 10), match='go_ipfs.py'>
>>> re.match('[a-zA-Z-0-9.-_]*', 'go_ipfs.py')
```

**Comment by alexander255** [comment]
Thanks @heaven00 for looking into this! This thing is really overdue…

After reading through the diff, I can see one (and only one) problem: You seem to have mixed up regular expressions (in particular PCRE) and `fnmatch`. These aren't the same thing; in particular: `fnmatch:* == pcre:.*`, `fnmatch:*ipfs* == pcre:.*ipfs.*` and `fnmatch:.ipfs. == pcre:\.ipfs\.`. Also check out the [Python documentation](https://docs.python.org/3/library/fnmatch.html) on this.

Finally regarding you comment about `[a-zA-Z-0-9.-_]*`: Yes, it will match `ipfs.py`, but what about `Things to do: A short list.txt` or `That über cool 寿司 recipe.doc`? `*` would match both, while the example you provided (there is no equivalent of that in fnmatch actually) is both more complex and would not work.

Note to self: We should probably extend fnmatch functionality in the future (not this PR), by:
 * Allowing multiple patterns to be passed as a list
 * Allowing a raw regular expression to be passed instead

**Comment by heaven00** [comment]
@alexander255 yes I have, thanks for the info :)

will change `re.match` to `fnmatch.fnmatch` that will also change the patterns back to `*`

P.S. thanks for the quick review, will push out the changes asap

**Comment by alexander255** [comment]
That was very soon indeed! Code now looks good to me! :+1:

**Comment by heaven00** [comment]
YaY! :D

**Pull request merged**
