### PR TITLE
Add log and bitswap cmd

### PR DESCRIPTION
**Pull request by fredthomsen**
Added more API commands to improve this relative to js-ipfs-api as mentioned by #42.

### CODE REVIEW

**Comment by whereswaldon** [comment]
I wish we'd known that you were doing those log commands. My team just implemented them as well #46 , but we don't have the bitswap stuff. We do have tests for the log functionality though.

**Comment by fredthomsen** [comment]
No worries.  How would you like to move forward and do you need any help?

**Comment by whereswaldon** [comment]
Well, I think both PRs should be merged, but I would suggest keeping our implementation of the log commands since it's tested. As for help, we only managed to cover most of the core API spec. There are a bunch of extensions missing if you're looking for another area to work on.

**Comment by alexander255** [comment]
Since @whereswaldon's log command has landed…

Could you open a new MR @fredthomsen with just the bitswap commit and (if you have the time for it) an accompanying unit test?
Thanks for helping out!

**Comment by whereswaldon** [comment]
@fredthomsen Really would love to merge your bitswap commands. Do you have time to write some tests and submit a new PR?

**Comment by fredthomsen** [comment]
Yes.  I'll re-open a separate pull request as suggested.

**Comment by fredthomsen** [comment]
#55 will replace this PR for the bitswap commands.

**Pull request closed without merging**
