### PR TITLE
Release version 0.4.2

### PR DESCRIPTION
**Pull request by alexander255**
“Restore feature-parity with go-IPFS 0.4.10”

### CODE REVIEW

**Comment by alexander255** [comment]
This is now uploaded. The version is `0.4.2.post1` because you cannot currently fix the description on PyPI without uploading a new version: https://github.com/pypa/warehouse/issues/2170

**Comment by mguentner** [comment]
Could you please tag `0.4.2.post1` / push the tag to github?

**Comment by alexander255** [comment]
There is no code change between `0.4.2` and "`0.4.2.post1`" was never released as such. The only difference were adding a few characters to the `README.md` to get `pandoc` to convert it to syntactically valid restructedText. 

Is there any reason you cannot use the `0.4.2` release tag from GIT?

**Comment by mguentner** [comment]
Yes. The reason is that the tag has not been pushed:

https://github.com/ipfs/py-ipfs-api/tags

**Comment by alexander255** [comment]
That's weird… Did GIT stop uploading tags automatically in some recent change!?

Anyway, it should be fixed now. Tag `0.4.2` is now a thing.

**Comment by mguentner** [comment]
Yeah, thank you!

**Pull request merged**
