### PR TITLE
Fix pre-commit script

### PR DESCRIPTION
**Pull request by suzaku**
There's no `pep8` environment configured in `tox.ini`.
We should use `codestyle` instead.

### CODE REVIEW

**Comment by whereswaldon** [comment]
@suzaku Could you rebase onto master? I don't seem to have permission to do it for you.

**Comment by suzaku** [comment]
@whereswaldon  Sure.

**Comment by suzaku** [comment]
Rebased.

**Comment by whereswaldon** [comment]
@suzaku Thank you!

**Pull request merged**
