### PR TITLE
Generate Sphinx documentation with Napoleon

### LINKED ISSUE #5: No pydoc documentation
The methods on an API client object have no documentation:

    >>> import ipfsApi
    >>> api = ipfsApi.Client()
    >>> help(api.ls)

This yields documentation on the `partial`  class, which isn't terribly helpful.  It is also impossible to ask for documentation on these methods using `pydoc`:

    $ pydoc ipfsApi.Client.ls
    no Python documentation found for 'ipfsApi.Client.ls'

This all seems very developer-unfriendly.

### PR DESCRIPTION
**Pull request by alexander255**
Quite a huge change, revised pretty much all API documentation we have had. Fixes #5 & #58.

Rendered result:
fs:/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/

### CODE REVIEW

**Comment by alexander255** [comment]
I also removed that old Python 2.6 coverage settings file and added keyword arguments for some stuff that previously required the use of `opts={…}`.

**Comment by whereswaldon** [comment]
Wow... Sorry that it took me so long to look at this. This is awesome. Should we add a link to the docs (via the IPFS gateway site) to the Readme? :+1: From me.

**Comment by alexander255** [comment]
Thanks for looking at this! Any comments on the added code? Particularly any problems you suspect?

<strong>Regarding documentation link:</strong>
Should I add an IPFS link (permanent), will have to be updated regularily, or an IPNS link (slower, gives node owner the power to update the link). Also currently I'm hosting the documentation from my server, should it stay that way, or should somebody else do this? In particular who should control the IPNS key?
I'd also like your opinion on this @jbenet.

**Comment by jbenet** [comment]
I think for now (until we solve the IPNS persistence story easily), i'd use a `dnslink`. See how `dist.ipfs.io` work. This unpublished post describes more https://github.com/ipfs/blog/pull/31/files

**Comment by jbenet** [comment]
We could do `pydoc.ipfs.io` or something? not sure. 

cc @lgierth @RichardLitt

**Comment by RichardLitt** [comment]
`pydoc.ipfs.io` sounds good to me!

**Comment by alexander255** [comment]
@RichardLitt: How would that entry be updated/set?
In particular: Is it possible to have the documentation updated whenever we merge new code into master (using the CI system for instance)?

**Comment by jbenet** [comment]
> (using the CI system for instance)?

If we use a secured CI system with env vars that are passed in securely yeah.

We've been meaning to setup "deploy to dnslink on merge" for a while. this could be a really nifty thing to setup with `heroku`. all the code for "hook up to github" should exist in libs in pypi or npm land. We could have a bot that either:
- deploys on merge
- or listens for something said in merged PRs only: `@botname please deploy to <dns-name>` or just `@botname please deploy` with some domain config in a file in the repo or something.

This ties into ipfs-pages some (cc @lgierth @RichardLitt ), and we could use it in our blog, and all the websites (ipld.io, multiformats.io, ipfs.io, etc)

**Comment by whereswaldon** [comment]
@alexander255 I looked at the code, but I'm not familiar enough with Sphinx to comment on the configuration there. The documentation changes are fine by me, and I didn't see anything that raised red flags in the actual code that was added (the functional test). Your other changes all seemed to be documentation or variable renaming. Did I miss something?

@jbenet That sounds like an awesome system to create, whether it be bot-based or within the Travis config.

**Comment by alexander255** [comment]
@whereswaldon Thanks, I'll merge it then. The Sphinx stuff is mostly just whatever `sphinx-quickstart` considered to be a good idea plus the example code snippets from the napoleon and recommonmark libraries – nothing fancy there. The largest code change was probably that many things that previously required the use of `opts` are now available as keyword parameters.
I also just remembered that we should probably hook this up to `tox` to simplify CI integration (in whatever form that will happen).

Thanks for looking into a permanent deployment solution @jbenet, do you have any timeframe when this would happen? Should we link to the above IPNS link in the mean time, and have me update it occasionally (as a stop-gap measure)?

**Comment by alexander255** [comment]
I'll just link to the IPNS resource above in the mean time.

**Pull request merged**
